-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

-- MAGIC %python
-- MAGIC import sys
-- MAGIC
-- MAGIC sys.path.append("/Workspace/Users/jorgeenriquecatano@hotmail.com/Test-learning")

-- COMMAND ----------

use catalog `workspace`;
use schema IDENTIFIER('test');

SELECT current_catalog(), current_schema()

-- COMMAND ----------

DESCRIBE SCHEMA EXTENDED `test`

-- COMMAND ----------

SHOW TABLES;

-- COMMAND ----------


SHOW VOLUMES;

-- COMMAND ----------

-- MAGIC %python
-- MAGIC spark.sql(f'''
-- MAGIC SELECT * 
-- MAGIC FROM csv.`/Volumes/workspace/test/pii`
-- MAGIC ''').display()

-- COMMAND ----------

-- MAGIC %python
-- MAGIC spark.sql(f'''
-- MAGIC SELECT * 
-- MAGIC FROM text.`/Volumes/workspace/test/pii`
-- MAGIC ''').limit(10).display()

-- COMMAND ----------


SELECT * 
FROM read_files(
  '/Volumes/workspace/test/pii/',
  format=>'csv',
  header=>'true',
  inferSchema=>'true'
)

-- COMMAND ----------

DROP TABLE IF EXISTS pii_patients;
    
CREATE TABLE pii_patients AS
SELECT 
patient_id,first_name,last_name,date_of_birth,race,weight,height,event_type,event_date,event_name,provider_name,reason,result,details,notes
FROM read_files(
  '/Volumes/workspace/test/pii/',
  format=>'csv',
  header=>'true',
  inferSchema=>'true'
);

SELECT * FROM pii_patients

-- COMMAND ----------

DESCRIBE pii_patients

-- COMMAND ----------

-- MAGIC %python
-- MAGIC #
-- MAGIC # Read CSV file and create a Spark dataframe
-- MAGIC #
-- MAGIC
-- MAGIC sdf =  (spark
-- MAGIC        .read
-- MAGIC        .format("csv")
-- MAGIC        .option("header", "true")
-- MAGIC        .option("inferSchema", "true")
-- MAGIC        .load("/Volumes/workspace/test/pii")
-- MAGIC        )
-- MAGIC        
-- MAGIC #
-- MAGIC # Creatye delta table
-- MAGIC #
-- MAGIC
-- MAGIC (sdf
-- MAGIC  .write
-- MAGIC  .mode("overwrite")
-- MAGIC  .format("delta")
-- MAGIC  .saveAsTable(f"pii_patients_py")
-- MAGIC )   

-- COMMAND ----------

-- MAGIC %python
-- MAGIC
-- MAGIC spark.read.table("pii_patients_py").display()

-- COMMAND ----------

-- MAGIC %python
-- MAGIC spark.catalog.listTables()

-- COMMAND ----------

DESCRIBE DETAIL pii_patients

-- COMMAND ----------

describe extended pii_patients;

-- COMMAND ----------


drop table if exists pii_patients_2;

create table workspace.test.pii_patients_2 as
select * from pii_patients

-- COMMAND ----------


DESCRIBE HISTORY workspace.test.pii_patients_2

-- COMMAND ----------


update workspace.test.pii_patients_2 set date_of_birth="1979-09-12" where patient_id="pmc-6431471-1"

-- COMMAND ----------

-- MAGIC %md
-- MAGIC

-- COMMAND ----------


select * from workspace.test.pii_patients_2 version as of 0;
